# -*- coding: utf-8 -*-
"""P-103.csv

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IStmrYZy7wLsKMDgNZujmLiONxYHiiwy
"""

import pandas as pd
import plotly.express as px
from google.colab import files
data_to_load=files.upload()
df=pd.read_csv('Covid data.csv')
fig=px.scatter(df,x='date',
y='cases',
color='country',
 size='cases')
fig.show()